### ISSUE TITLE
Visões individuas do 5w2h

### ISSUE THREAD

**Issue by italovinicius18** [UnBArqDsw2021-2/2021.2_G3_stag.io#1]
## Descrição da issue
Pessoal, para facilitar no desenvolvimento individual do 5w2h, criei esta issue que será refletida na página de pré-rastrebilidade e assim facilita em criar a visão do grupo em relação ao 5w2h.

Como será feito?

Cada integrante elaborará um 5w2h para permitir uma visualização mais ampla do domínio do problema, por isso solicito que respondam às perguntas abaixo baseado-se na aplicação que será desenvolvida

What (O quê será feito?);
Where(Onde será feito?);
When(Quando será feito?);
Why(Por quê será feito?);
Who(Por Quem será feito?);
How(Como será feito?);
How Much(Quanto irá custar?).

## Contexto adicional

Quando nos reunirmos vamos abstrair melhor estas visões e criamos uma visão geral do grupo, facilitando no melhor entendimento geral do grupo de qual será o escopo do Stag.io.

## Tópicos:
- [ ] Todo integrante elaborou um 5w2h
- [x] A visão do grupo foi elaborada

**Comment by italovinicius18** [comment]
| What (O quê será feito?) | Where(Onde será feito?) | When(Quando será feito?) | Why(Por quê será feito?) | Who(Por Quem será feito?) | How(Como será feito?) | How Much(Quanto irá custar?) |
|--|--|--|--|--|--|--|
|Uma aplicação que reúne vagas de estágio em empresas e oferece estas vagas aos possíveis interessados, facilitando que encontrem essa categoria de trabalho| Através de uma aplicação web| Durante o segundo semestre letivo de 2021 (17/01/22 a 05/05/22)|Para facilitar a relação entre empresa-interessado, facilitando com que ele tenha uma fonte específica para o tema de estágio e não precise procurar esta categoria de vaga ao meio de tipos diferentes de regimes trabalhistas|Grupo 03 da matéria de ArqDS|Serão estudadas as plataformas que oferecem diferentes tipos de trabalhos e partir de um ponto de vista focado no interessado no estágio, vamos observar quais são os pontos positivos para que esta pessoa tenha facilidade de encontrar a vaga de interesse e possua as informações da vaga de qual a situação dela| A definir |

**Comment by gabrielavelino** [comment]
| What (O quê será feito?) | Where(Onde será feito?) | When(Quando será feito?) | Why(Por quê será feito?) | Who(Por Quem será feito?) | How(Como será feito?) | How Much(Quanto irá custar?) |
|--|--|--|--|--|--|--|
|Um website que divulga vagas somente de estágios de empresas para os interessados, visando facilitar a busca por empregos do tipo estágio| Será feito um site| Durante o semestre do curso de ArqDS| Para facilitar a busca por esse tipo de categoria de emprego que seria o estágio, visando acelerar e facilitar as ofertas das empresas e os que buscam estágio| Grupo 03 da matéria de ArqDS| Será realizado uma pesquisa de campo nas plataformas disponíveis, e buscar os recursos necessários que atendem o usuário que busca somente estágios | Custo das ferramentas de programação |

**Comment by IanFPFerreira** [comment]
| What (O quê será feito?) | Where (Onde será feito?) | When (Quando será feito?) | Why (Por quê será feito?) | Who (Por Quem será feito?) | How (Como será feito?) | How Much (Quanto irá custar?) |
|--|--|--|--|--|--|--|
| Uma aplicação Web especializada na divulgação de vagas de estágio por parte das empresas cadastradas, e a marcação de interesse nessas vagas por parte das pessoas que buscam esse tipo de trabalho  | O projeto será uma aplicação Web | Durante o segundo semestre letivo de 2021 que vai de 17/01/22 até 05/05/22 | Porque é uma aplicação que visa ajudar estudantes, universitários e outras pessoas interessadas em encontrar oportunidades nessa modalidade de trabalho que é o estágio, já que é uma modalidade que comumente está interessada em pessoas ainda no processo de aprendizado | Grupo 03 da matéria de ArqDS | Será feito reuniões semanais no intuito de ver o andamento de todo o projeto e planejar as próximas tarefas, sendo que cada tarefa possuirá uma ou mais pessoas para realizá-la e uma ou mais pessoas para revisar essa tarefa feita | Custará o tempo que cada membro terá que gastar para realizar o projeto |

**Comment by joaovaladao** [comment]
| What (O quê será feito?) | Where(Onde será feito?) | When(Quando será feito?) | Why(Por quê será feito?) | Who(Por Quem será feito?) | How(Como será feito?) | How Much(Quanto irá custar?) |
|--|--|--|--|--|--|--|
|Desenvolver uma aplicação web para agrupar vagas de estágio e assim facilitar sua procura| Desenvolvimento Web (site) | 17/01/22 a 05/05/22 |Devido a dificuldade de procura por vagas online, já que raramente podem ser encontradas em uma única plataforma, nossa aplicação visa auxiliar os estudantes nessa etapa de suas vidas | Grupo 03 | Por meio dos conhecimentos prévios do grupo e pesquisas com os integrantes para definir uma linguagem e as plataformas que serão utilizadas| -----------|

**Comment by Nathanserra** [comment]
What  | Where | When  | Why  | Who | How  | How Much 
|-- | -- | -- | -- | -- | -- | --|
|Um site com o propósito de facilitar a divulgação de vagas de estágio e estudantes interessados | Será feito de maneira remota pelo integrantes do grupo | Durante o segundo semestre letivo de 2021 que vai de 17/01/22 até 05/05/22 | Para facilitar a divulgação de estágios por uma plataforma transparente e ajudar na diminuição da escassez de plataformas com este propósito | Grupo 03 da matéria de ArqDS | Por meio de tecnologias voltadas para o desenvolvimento de software seguindo as instruções e aprendizagens no curso de ArqDS | Não terá custo financeiro, somente o tempo dos integrantes do grupo |

**Comment by hryds** [comment]
| What (O que será feito?)| Where (Onde será feito?)| When (Quando será feito?)| Why (Por quê será feito?)| Who (Por Quem será feito?)| How (Como será feito?) | How Much (Quanto irá custar?) |
| -- | -- | -- | -- | -- | -- | -- |
| Uma aplicação web para reunir vagas específicas para estágios | Remotamente | Durante o 2º Semestre  letivo de 2021 (17/01/2022 a 05/05/2022)| Para facilitar a busca por vagas específicas para estágio e a comunicação inicial entre empresas e candidatos de diversos perfis| Grupo 03 da matéria de Arquitetura e Desenho de Software  | Empresas poderão cadastrar vagas disponíveis, enquanto candidatos poderão cadastrar seus currículos e registrar interesse em determinadas vagas| Tempo de dedicação dos membros da equipe no desenvolvimento do projeto |

**Comment by italofernandes13** [comment]
|What (O quê será feito?)|Where(Onde será feito?)|When(Quando será feito?)|Why(Por quê será feito?)|Who(Por Quem será feito?)|How(Como será feito?)|How Much(Quanto irá custar?)|
|--|--|--|--|--|--|--|
|Será feito um website com a finalidade de divulgar e facilitar a contratação de estágios|Será desenvolvido um website|Durante o segundo semestre letivo de 2021|Para facilitar a procura e divulgação de com foco no estágio e sua comunicação entre os interessados|Grupo 03 da matéria de ArqDS|Através de uma análise de plataformas e sites de estágios com o objetivo de obter vários pontos de vistas diferentes para assim desenvolver um website focado para estágios|custará tempo de cada integrante do grupo|

**Comment by guilhermemoraisr** [comment]
<html>
<body>


What (O quê será feito?) | Where(Onde será feito?) | When(Quando será feito?) | Why(Por quê será feito?) | Who(Por Quem será feito?) | How(Como será feito?) | How Much(Quanto irá custar?)
-- | -- | -- | -- | -- | -- | --
Uma aplicação web que disponibilize de forma integrada e simplificada um sistema de oferta e demanda de vagas de estágio, publicadas pelas empresas e aplicadas sob interesses pelos estudantes. | Será um website | Durante o segundo semestre letivo de 2021 (17/01/22 a 05/05/22) | O grupo observou que há uma problemática no mercado de estágios, visto que percebe-se que principalmente a divulgação de vagas e captação de candidatos é muito difusa | Grupo 03 da matéria de ArqDS | O grupo irá desenvolver de forma coletiva e por partes o sistema completo do zero, utilizando tecnologias próprias para produzir websites | O tempo e dedicação necessários para desenvolver todos as funções propostas.


</body>
</html>
