### ISSUE TITLE
RichPicture

### ISSUE THREAD

**Issue by joaovaladao** [UnBArqDsw2021-2/2021.2_G3_stag.io#3]
## Descrição da issue
Dividição da equipe em trios para a realização de 3 versões diferentes de Rich Picture para diversificação de ideias e visões acerca do projeto

## Contexto adicional
Um Rich Picture é um artefato construído preferencialmente em colaboração com stakeholders a fim de ilustrar e, assim, trazer uma melhor compreensão do problema a ser resolvido pela equipe de desenvolvimento.

## Tópicos:
- [x] Definir quais serão os trios;
- [x] Agendar um horário de encontro para cada equipe;
- [ ] Cada equipe deve criar um fluxo do projeto e seus requisitos;
- [ ] Reunião para as equipes avaliarem todos os Rich Picture e definirem como será a versão final;

**Comment by italovinicius18** [comment]
Pessoal, a recomendação era de que o repositório seria forkado e assim criassem a branch, pois assim não teríamos problemas de branchs com nomes repetidos, porém agora como já fizeram o PR, gostaria que mudassem a estratégia, mudem o nome da branch para "RichPicture1" e assim os próximos coloquem como "RichPicture2" e assim por diante
