### ISSUE TITLE
Primeira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2021-2/2021.2_G3_stag.io#53]
Olá Pessoal!

O Grupo 03 irá avaliar o Grupo 04 nessa primeira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta acessar o Tópico 2 DSW(Base) no Moodle, e procurar por "Primeira Avaliação por Pares".

Deadline: 07 de Fevereiro de 2022, ao final do dia, conforme consta no cronograma.

Atenciosamente.

**Comment by AlvaroLeles** [comment]
07/02/2022: O grupo se reuniu no horário da aula e realizou a avaliação por pares discutindo juntos cada um dos tópicos.
